<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="12897" started-at="2021-01-18T10:57:55Z" finished-at="2021-01-18T10:58:08Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="12897" started-at="2021-01-18T10:57:55Z" finished-at="2021-01-18T10:58:08Z">
      <class name="test_Scripts.Valid_Login">
        <test-method status="PASS" signature="openAppl()[pri:0, instance:test_Scripts.Valid_Login@42dafa95]" name="openAppl" is-config="true" duration-ms="6256" started-at="2021-01-18T16:27:55Z" finished-at="2021-01-18T16:28:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openAppl -->
        <test-method status="FAIL" signature="login()[pri:0, instance:test_Scripts.Valid_Login@42dafa95]" name="login" duration-ms="5961" started-at="2021-01-18T16:28:01Z" finished-at="2021-01-18T16:28:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at test_Scripts.Valid_Login.login(Valid_Login.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="closeAppl(org.testng.ITestResult)[pri:0, instance:test_Scripts.Valid_Login@42dafa95]" name="closeAppl" is-config="true" duration-ms="664" started-at="2021-01-18T16:28:07Z" finished-at="2021-01-18T16:28:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=FAILURE method=Valid_Login.login()[pri:0, instance:test_Scripts.Valid_Login@42dafa95] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeAppl -->
      </class> <!-- test_Scripts.Valid_Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
